### ISSUE TITLE
Tests are broken on Python 3.5

### ISSUE THREAD

**Issue by teran-mckinney** [AustEcon/bitsv#31]
```
 #$ git log -1
commit 077ec9f80ddc74ca0fa5950aad5847ca71dea2b2
Author: cyborg0922 <cyborg.napster.0922@gmail.com>
Date:   Sun Jun 30 18:30:12 2019 +1200

    Make wif_to_key cleaner. Use different WIF and Addresses for STN.
 #$ nosetests -vx
Failure: SyntaxError (invalid syntax (bitindex3.py, line 49)) ... ERROR

======================================================================
ERROR: Failure: SyntaxError (invalid syntax (bitindex3.py, line 49))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/local/lib/python3.5/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python3.5/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python3.5/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.5/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.5/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/user/repos/bitsv/bitsv/__init__.py", line 2, in <module>
    from bitsv.network.rates import SUPPORTED_CURRENCIES, set_rate_cache_time
  File "/home/user/repos/bitsv/bitsv/network/__init__.py", line 6, in <module>
    from .services import NetworkAPI
  File "/home/user/repos/bitsv/bitsv/network/services/__init__.py", line 2, in <module>
    from .bitindex3 import (
  File "/home/user/repos/bitsv/bitsv/network/services/bitindex3.py", line 49
    f'https://api.bitindex.network/api/v3/{self.network}/addrs/utxo',
                                                                   ^
SyntaxError: invalid syntax

----------------------------------------------------------------------
Ran 1 test in 0.159s

FAILED (errors=1)
```

**Comment by teran-mckinney** [comment]
This is on Python 3.5, maybe that is why? I don't think we want to drop 3.5 yet.

**Comment by teran-mckinney** [comment]
https://cito.github.io/blog/f-strings/

f-strings are 3.6+.

**Comment by teran-mckinney** [comment]
Next up is bitcoinx, what do you think @AustEcon?

I opened this: https://github.com/kyuupichan/bitcoinX/issues/5

**Comment by AustEcon** [comment]
Yeah. I am planning to send the bip32 stuff off to its own repo and make it so that all of the bitsv stuff is nicely available at the "leaves of the tree". E.g. every bip32 derived key should give easy access to all bitsv functionality via inheritence... This would remove the bitcoinx dependency for bitsv but would still be present for the bip32 stuff. :)

And yes - I am quite happy to have the f-string stuff changed over to .format() syntax even though f-strings look way cooler 😆.

**Comment by teran-mckinney** [comment]
Ha, yes they do. Can you review my PR? #32

Going to bed now.
